spring:
  application:
    name: gateway
  config.import: optional:configserver:http://localhost:8888/
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: tenant-route
              uri: lb://TENANT-SERVICE
              predicates:
                - Path=/tenant/**
              filters:
                - RewritePath=/tenant/(?<segment>.*), /${segment}
            - id: auth-route
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**
              filters:
                - RewritePath=/auth/(?<segment>.*), /${segment}
            - id: role-route
              uri: lb://ROLE-SERVICE
              predicates:
              - Path=/role/**
              filters:
              - RewritePath=/role/(?<segment>.*), /${segment}
          # filters:
          #   - Auther
#        - id: auth-route
#          uri: lb://auth-server
#          predicates:
#            - Path=/login, /register, /internal/validatejwt
#      default-filters:
#        - Auther #The names of filters have to have -GatewayFilterFactory as a suffix in the class, but the suffix must not be included in the YAML
server:
  port: 8765