spring:
  application.name: role-service
  config.import: optional:configserver:http://localhost:8888/
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:${TENANT_DB_URL}
    username: ${TENANT_DB_USERNAME}
    password: ${TENANT_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 9000